---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu2204
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tty: True
scenario:
  name: default
  test_sequence:
    #- dependency
    #- lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - cleanup
    - destroy
provisioner:
  name: ansible
verifier:
  name: ansible
