---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    molecule_labels:
      owner: molecule
  tags:
    - always
  tasks:
    - name: Set async_dir for HOME env
      ansible.builtin.set_fact:
        ansible_async_dir: "{{ lookup('env', 'HOME') }}/.ansible_async/"
      when: (lookup('env', 'HOME'))

    - name: Create molecule instance(s)
      theko2fi.multipass.multipass_vm:
        name: "{{ item.name }}"
        cloud_init: "{{ item.cloud_init | default(omit) }}"
        cpus: "{{ item.cpu | default(omit) }}"
        disk: "{{ item.disk | default(omit) }}"
        image: "{{ item.image | default(omit) }}"
        memory: "{{ item.memory | default(omit) }}"
        recreate: "{{ item.recreate | default(omit) }}"
        state: 'started'
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: multipass_jobs
      until: multipass_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"