---
name: CI

on:
  - push
  - pull_request

jobs:
  test-job:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        molecule_distro:
          - image: ubuntu2204
            command: /lib/systemd/systemd
          - image: ubuntu2004
            command: /lib/systemd/systemd
          - image: ubuntu1804
            command: /lib/systemd/systemd
          - image: rockylinux9
            command: /usr/lib/systemd/systemd
          - image: rockylinux8
            command: /usr/lib/systemd/systemd
          - image: debian11
            command: /lib/systemd/systemd
          - image: debian10
            command: /lib/systemd/systemd
          - image: fedora38
            command: /usr/sbin/init
          - image: fedora37
            command: /usr/sbin/init
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "theko2fi.apache_guacamole"

      - name: install dependencies
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests
        run: |
          cd theko2fi.apache_guacamole
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro.image }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.molecule_distro.command }}
