---
name: publish to galaxy

on:
  release:
    types: [published]

jobs:
  release:
    name: Release to galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the version name from the tags
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: publish to ansible galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          api_key: '${{ secrets.galaxi_api_key }}'
          git_branch: main
